In [1]:
import pymongo
import pandas
import sqlite3

## Connexion à la base en SQLite

In [ ]:
conn = sqlite3.connect("world.sqlite")

In [ ]:
pandas.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)

              name
0             City
1          Country
2  CountryLanguage

On récupère les données des 3 tables présentes.

In [20]:
liste_tables = pandas.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)["name"]
for table in liste_tables:
    valeurs = pandas.read_sql_query("SELECT * FROM " + table + ";", conn)
    globals()[table] = valeurs

# on ferme la connexion à la base SQLite car ce n'est plus utile
conn.close()

In [21]:
City.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [22]:
Country.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL

In [23]:
CountryLanguage.head()

  CountryCode    Language IsOfficial  Percentage
0         ABW       Dutch          T         5.3
1         ABW     English          F         9.5
2         ABW  Papiamento          F        76.7
3         ABW     Spanish          F         7.4
4         AFG     Balochi          F         0.9

## Connexion à Mongo DB

In [24]:
client = pymongo.MongoClient()

# On va créer une nouvelle base de données nommée "world"
db = client.world

## Première possibilité : on fait une collection par table

In [52]:
[dict(zip(list(City), e)) for e in City.values.tolist()]

[{'ID': 1,
  'Name': 'Kabul',
  'CountryCode': 'AFG',
  'District': 'Kabol',
  'Population': 1780000},
 {'ID': 2,
  'Name': 'Qandahar',
  'CountryCode': 'AFG',
  'District': 'Qandahar',
  'Population': 237500},
 {'ID': 3,
  'Name': 'Herat',
  'CountryCode': 'AFG',
  'District': 'Herat',
  'Population': 186800},
 {'ID': 4,
  'Name': 'Mazar-e-Sharif',
  'CountryCode': 'AFG',
  'District': 'Balkh',
  'Population': 127800},
 {'ID': 5,
  'Name': 'Amsterdam',
  'CountryCode': 'NLD',
  'District': 'Noord-Holland',
  'Population': 731200},
 {'ID': 6,
  'Name': 'Rotterdam',
  'CountryCode': 'NLD',
  'District': 'Zuid-Holland',
  'Population': 593321},
 {'ID': 7,
  'Name': 'Haag',
  'CountryCode': 'NLD',
  'District': 'Zuid-Holland',
  'Population': 440900},
 {'ID': 8,
  'Name': 'Utrecht',
  'CountryCode': 'NLD',
  'District': 'Utrecht',
  'Population': 234323},
 {'ID': 9,
  'Name': 'Eindhoven',
  'CountryCode': 'NLD',
  'District': 'Noord-Brabant',
  'Population': 201843},
 {'ID': 10,
  'Name': 'Tilburg',
  'CountryCode': 'NLD',
  'District': 'Noord-Brabant',
  'Population': 193238},
 {'ID': 11,
  'Name': 'Groningen',
  'CountryCode': 'NLD',
  'District': 'Groningen',
  'Population': 172701},
 {'ID': 12,
  'Name': 'Breda',
  'CountryCode': 'NLD',
  'District': 'Noord-Brabant',
  'Population': 160398},
 {'ID': 13,
  'Name': 'Apeldoorn',
  'CountryCode': 'NLD',
  'District': 'Gelderland',
  'Population': 153491},
 {'ID': 14,
  'Name': 'Nijmegen',
  'CountryCode': 'NLD',
  'District': 'Gelderland',
  'Population': 152463},
 {'ID': 15,
  'Name': 'Enschede',
  'CountryCode': 'NLD',
  'District': 'Overijssel',
  'Population': 149544},
 {'ID': 16,
  'Name': 'Haarlem',
  'CountryCode': 'NLD',
  'District': 'Noord-Holland',
  'Population': 148772},
 {'ID': 17,
  'Name': 'Almere',
  'CountryCode': 'NLD',
  'District': 'Flevoland',
  'Population': 142465},
 {'ID': 18,
  'Name': 'Arnhem',
  'CountryCode': 'NLD',
  'District': 'Gelderland',
  'Population': 138020},
 {'ID': 19,
  'Name': 'Zaanstad',
  'CountryCode': 'NLD',
  'District': 'Noord-Holland',
  'Population': 135621},
 {'ID': 20,
  'Name': '´s-Hertogenbosch',
  'CountryCode': 'NLD',
  'District': 'Noord-Brabant',
  'Population': 129170},
 {'ID': 21,
  'Name': 'Amersfoort',
  'CountryCode': 'NLD',
  'District': 'Utrecht',
  'Population': 126270},
 {'ID': 22,
  'Name': 'Maastricht',
  'CountryCode': 'NLD',
  'District': 'Limburg',
  'Population': 122087},
 {'ID': 23,
  'Name': 'Dordrecht',
  'CountryCode': 'NLD',
  'District': 'Zuid-Holland',
  'Population': 119811},
 {'ID': 24,
  'Name': 'Leiden',
  'CountryCode': 'NLD',
  'District': 'Zuid-Holland',
  'Population': 117196},
 {'ID': 25,
  'Name': 'Haarlemmermeer',
  'CountryCode': 'NLD',
  'District': 'Noord-Holland',
  'Population': 110722},
 {'ID': 26,
  'Name': 'Zoetermeer',
  'CountryCode': 'NLD',
  'District': 'Zuid-Holland',
  'Population': 110214},
 {'ID': 27,
  'Name': 'Emmen',
  'CountryCode': 'NLD',
  'District': 'Drenthe',
  'Population': 105853},
 {'ID': 28,
  'Name': 'Zwolle',
  'CountryCode': 'NLD',
  'District': 'Overijssel',
  'Population': 105819},
 {'ID': 29,
  'Name': 'Ede',
  'CountryCode': 'NLD',
  'District': 'Gelderland',
  'Population': 101574},
 {'ID': 30,
  'Name': 'Delft',
  'CountryCode': 'NLD',
  'District': 'Zuid-Holland',
  'Population': 95268},
 {'ID': 31,
  'Name': 'Heerlen',
  'CountryCode': 'NLD',
  'District': 'Limburg',
  'Population': 95052},
 {'ID': 32,
  'Name': 'Alkmaar',
  'CountryCode': 'NLD',
  'District': 'Noord-Holland',
  'Population': 92713},
 {'ID': 33,
  'Name': 'Willemstad',
  'CountryCode': 'ANT',
  'District': 'Curaçao',
  'Population': 2345},
 {'ID': 34,
  'Name': 'Tirana',
  'CountryCode': 'ALB',
  'District': 'Tirana',
  'Population': 270000},
 {'ID': 35,
  'Name': 'Alger',
  'CountryCode': 'DZA',
  'District': 'Alger',
  'Population': 2168000},
 {'ID': 36,
  'Name': 'Oran',
  'CountryCode': 'DZA',
  'District': 'Oran',
  'Population': 609823},
 {'ID': 37,
  'Name': 'Constantine',
  'CountryCode': 'DZA',
  'District': 'Constantine',
  'Population': 443727},
 {'ID': 38,
  'Name': 'Annaba',
  'CountryCode': 'DZA',
  'District': 'Annaba',
  'Population': 222518},
 {'ID': 39,
  'Name': 'Batna',
  'CountryCode': 'DZA',
  'District': 'Batna',
  'Population': 183377},
 {'ID': 40,
  'Name': 'Sétif',
  'CountryCode': 'DZA',
  'District': 'Sétif',
  'Population': 179055},
 {'ID': 41,
  'Name': 'Sidi Bel Abbès',
  'CountryCode': 'DZA',
  'District': 'Sidi Bel Abbès',
  'Population': 153106},
 {'ID': 42,
  'Name': 'Skikda',
  'CountryCode': 'DZA',
  'District': 'Skikda',
  'Population': 128747},
 {'ID': 43,
  'Name': 'Biskra',
  'CountryCode': 'DZA',
  'District': 'Biskra',
  'Population': 128281},
 {'ID': 44,
  'Name': 'Blida (el-Boulaida)',
  'CountryCode': 'DZA',
  'District': 'Blida',
  'Population': 127284},
 {'ID': 45,
  'Name': 'Béjaïa',
  'CountryCode': 'DZA',
  'District': 'Béjaïa',
  'Population': 117162},
 {'ID': 46,
  'Name': 'Mostaganem',
  'CountryCode': 'DZA',
  'District': 'Mostaganem',
  'Population': 115212},
 {'ID': 47,
  'Name': 'Tébessa',
  'CountryCode': 'DZA',
  'District': 'Tébessa',
  'Population': 112007},
 {'ID': 48,
  'Name': 'Tlemcen (Tilimsen)',
  'CountryCode': 'DZA',
  'District': 'Tlemcen',
  'Population': 110242},
 {'ID': 49,
  'Name': 'Béchar',
  'CountryCode': 'DZA',
  'District': 'Béchar',
  'Population': 107311},
 {'ID': 50,
  'Name': 'Tiaret',
  'CountryCode': 'DZA',
  'District': 'Tiaret',
  'Population': 100118},
 {'ID': 51,
  'Name': 'Ech-Chleff (el-Asnam)',
  'CountryCode': 'DZA',
  'District': 'Chlef',
  'Population': 96794},
 {'ID': 52,
  'Name': 'Ghardaïa',
  'CountryCode': 'DZA',
  'District': 'Ghardaïa',
  'Population': 89415},
 {'ID': 53,
  'Name': 'Tafuna',
  'CountryCode': 'ASM',
  'District': 'Tutuila',
  'Population': 5200},
 {'ID': 54,
  'Name': 'Fagatogo',
  'CountryCode': 'ASM',
  'District': 'Tutuila',
  'Population': 2323},
 {'ID': 55,
  'Name': 'Andorra la Vella',
  'CountryCode': 'AND',
  'District': 'Andorra la Vella',
  'Population': 21189},
 {'ID': 56,
  'Name': 'Luanda',
  'CountryCode': 'AGO',
  'District': 'Luanda',
  'Population': 2022000},
 {'ID': 57,
  'Name': 'Huambo',
  'CountryCode': 'AGO',
  'District': 'Huambo',
  'Population': 163100},
 {'ID': 58,
  'Name': 'Lobito',
  'CountryCode': 'AGO',
  'District': 'Benguela',
  'Population': 130000},
 {'ID': 59,
  'Name': 'Benguela',
  'CountryCode': 'AGO',
  'District': 'Benguela',
  'Population': 128300},
 {'ID': 60,
  'Name': 'Namibe',
  'CountryCode': 'AGO',
  'District': 'Namibe',
  'Population': 118200},
 {'ID': 61,
  'Name': 'South Hill',
  'CountryCode': 'AIA',
  'District': '–',
  'Population': 961},
 {'ID': 62,
  'Name': 'The Valley',
  'CountryCode': 'AIA',
  'District': '–',
  'Population': 595},
 {'ID': 63,
  'Name': 'Saint John´s',
  'CountryCode': 'ATG',
  'District': 'St John',
  'Population': 24000},
 {'ID': 64,
  'Name': 'Dubai',
  'CountryCode': 'ARE',
  'District': 'Dubai',
  'Population': 669181},
 {'ID': 65,
  'Name': 'Abu Dhabi',
  'CountryCode': 'ARE',
  'District': 'Abu Dhabi',
  'Population': 398695},
 {'ID': 66,
  'Name': 'Sharja',
  'CountryCode': 'ARE',
  'District': 'Sharja',
  'Population': 320095},
 {'ID': 67,
  'Name': 'al-Ayn',
  'CountryCode': 'ARE',
  'District': 'Abu Dhabi',
  'Population': 225970},
 {'ID': 68,
  'Name': 'Ajman',
  'CountryCode': 'ARE',
  'District': 'Ajman',
  'Population': 114395},
 {'ID': 69,
  'Name': 'Buenos Aires',
  'CountryCode': 'ARG',
  'District': 'Distrito Federal',
  'Population': 2982146},
 {'ID': 70,
  'Name': 'La Matanza',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 1266461},
 {'ID': 71,
  'Name': 'Córdoba',
  'CountryCode': 'ARG',
  'District': 'Córdoba',
  'Population': 1157507},
 {'ID': 72,
  'Name': 'Rosario',
  'CountryCode': 'ARG',
  'District': 'Santa Fé',
  'Population': 907718},
 {'ID': 73,
  'Name': 'Lomas de Zamora',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 622013},
 {'ID': 74,
  'Name': 'Quilmes',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 559249},
 {'ID': 75,
  'Name': 'Almirante Brown',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 538918},
 {'ID': 76,
  'Name': 'La Plata',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 521936},
 {'ID': 77,
  'Name': 'Mar del Plata',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 512880},
 {'ID': 78,
  'Name': 'San Miguel de Tucumán',
  'CountryCode': 'ARG',
  'District': 'Tucumán',
  'Population': 470809},
 {'ID': 79,
  'Name': 'Lanús',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 469735},
 {'ID': 80,
  'Name': 'Merlo',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 463846},
 {'ID': 81,
  'Name': 'General San Martín',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 422542},
 {'ID': 82,
  'Name': 'Salta',
  'CountryCode': 'ARG',
  'District': 'Salta',
  'Population': 367550},
 {'ID': 83,
  'Name': 'Moreno',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 356993},
 {'ID': 84,
  'Name': 'Santa Fé',
  'CountryCode': 'ARG',
  'District': 'Santa Fé',
  'Population': 353063},
 {'ID': 85,
  'Name': 'Avellaneda',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 353046},
 {'ID': 86,
  'Name': 'Tres de Febrero',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 352311},
 {'ID': 87,
  'Name': 'Morón',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 349246},
 {'ID': 88,
  'Name': 'Florencio Varela',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 315432},
 {'ID': 89,
  'Name': 'San Isidro',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 306341},
 {'ID': 90,
  'Name': 'Tigre',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 296226},
 {'ID': 91,
  'Name': 'Malvinas Argentinas',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 290335},
 {'ID': 92,
  'Name': 'Vicente López',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 288341},
 {'ID': 93,
  'Name': 'Berazategui',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 276916},
 {'ID': 94,
  'Name': 'Corrientes',
  'CountryCode': 'ARG',
  'District': 'Corrientes',
  'Population': 258103},
 {'ID': 95,
  'Name': 'San Miguel',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 248700},
 {'ID': 96,
  'Name': 'Bahía Blanca',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 239810},
 {'ID': 97,
  'Name': 'Esteban Echeverría',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 235760},
 {'ID': 98,
  'Name': 'Resistencia',
  'CountryCode': 'ARG',
  'District': 'Chaco',
  'Population': 229212},
 {'ID': 99,
  'Name': 'José C. Paz',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 221754},
 {'ID': 100,
  'Name': 'Paraná',
  'CountryCode': 'ARG',
  'District': 'Entre Rios',
  'Population': 207041},
 {'ID': 101,
  'Name': 'Godoy Cruz',
  'CountryCode': 'ARG',
  'District': 'Mendoza',
  'Population': 206998},
 {'ID': 102,
  'Name': 'Posadas',
  'CountryCode': 'ARG',
  'District': 'Misiones',
  'Population': 201273},
 {'ID': 103,
  'Name': 'Guaymallén',
  'CountryCode': 'ARG',
  'District': 'Mendoza',
  'Population': 200595},
 {'ID': 104,
  'Name': 'Santiago del Estero',
  'CountryCode': 'ARG',
  'District': 'Santiago del Estero',
  'Population': 189947},
 {'ID': 105,
  'Name': 'San Salvador de Jujuy',
  'CountryCode': 'ARG',
  'District': 'Jujuy',
  'Population': 178748},
 {'ID': 106,
  'Name': 'Hurlingham',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 170028},
 {'ID': 107,
  'Name': 'Neuquén',
  'CountryCode': 'ARG',
  'District': 'Neuquén',
  'Population': 167296},
 {'ID': 108,
  'Name': 'Ituzaingó',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 158197},
 {'ID': 109,
  'Name': 'San Fernando',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 153036},
 {'ID': 110,
  'Name': 'Formosa',
  'CountryCode': 'ARG',
  'District': 'Formosa',
  'Population': 147636},
 {'ID': 111,
  'Name': 'Las Heras',
  'CountryCode': 'ARG',
  'District': 'Mendoza',
  'Population': 145823},
 {'ID': 112,
  'Name': 'La Rioja',
  'CountryCode': 'ARG',
  'District': 'La Rioja',
  'Population': 138117},
 {'ID': 113,
  'Name': 'San Fernando del Valle de Cata',
  'CountryCode': 'ARG',
  'District': 'Catamarca',
  'Population': 134935},
 {'ID': 114,
  'Name': 'Río Cuarto',
  'CountryCode': 'ARG',
  'District': 'Córdoba',
  'Population': 134355},
 {'ID': 115,
  'Name': 'Comodoro Rivadavia',
  'CountryCode': 'ARG',
  'District': 'Chubut',
  'Population': 124104},
 {'ID': 116,
  'Name': 'Mendoza',
  'CountryCode': 'ARG',
  'District': 'Mendoza',
  'Population': 123027},
 {'ID': 117,
  'Name': 'San Nicolás de los Arroyos',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 119302},
 {'ID': 118,
  'Name': 'San Juan',
  'CountryCode': 'ARG',
  'District': 'San Juan',
  'Population': 119152},
 {'ID': 119,
  'Name': 'Escobar',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 116675},
 {'ID': 120,
  'Name': 'Concordia',
  'CountryCode': 'ARG',
  'District': 'Entre Rios',
  'Population': 116485},
 {'ID': 121,
  'Name': 'Pilar',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 113428},
 {'ID': 122,
  'Name': 'San Luis',
  'CountryCode': 'ARG',
  'District': 'San Luis',
  'Population': 110136},
 {'ID': 123,
  'Name': 'Ezeiza',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 99578},
 {'ID': 124,
  'Name': 'San Rafael',
  'CountryCode': 'ARG',
  'District': 'Mendoza',
  'Population': 94651},
 {'ID': 125,
  'Name': 'Tandil',
  'CountryCode': 'ARG',
  'District': 'Buenos Aires',
  'Population': 91101},
 {'ID': 126,
  'Name': 'Yerevan',
  'CountryCode': 'ARM',
  'District': 'Yerevan',
  'Population': 1248700},
 {'ID': 127,
  'Name': 'Gjumri',
  'CountryCode': 'ARM',
  'District': 'Širak',
  'Population': 211700},
 {'ID': 128,
  'Name': 'Vanadzor',
  'CountryCode': 'ARM',
  'District': 'Lori',
  'Population': 172700},
 {'ID': 129,
  'Name': 'Oranjestad',
  'CountryCode': 'ABW',
  'District': '–',
  'Population': 29034},
 {'ID': 130,
  'Name': 'Sydney',
  'CountryCode': 'AUS',
  'District': 'New South Wales',
  'Population': 3276207},
 {'ID': 131,
  'Name': 'Melbourne',
  'CountryCode': 'AUS',
  'District': 'Victoria',
  'Population': 2865329},
 {'ID': 132,
  'Name': 'Brisbane',
  'CountryCode': 'AUS',
  'District': 'Queensland',
  'Population': 1291117},
 {'ID': 133,
  'Name': 'Perth',
  'CountryCode': 'AUS',
  'District': 'West Australia',
  'Population': 1096829},
 {'ID': 134,
  'Name': 'Adelaide',
  'CountryCode': 'AUS',
  'District': 'South Australia',
  'Population': 978100},
 {'ID': 135,
  'Name': 'Canberra',
  'CountryCode': 'AUS',
  'District': 'Capital Region',
  'Population': 322723},
 {'ID': 136,
  'Name': 'Gold Coast',
  'CountryCode': 'AUS',
  'District': 'Queensland',
  'Population': 311932},
 {'ID': 137,
  'Name': 'Newcastle',
  'CountryCode': 'AUS',
  'District': 'New South Wales',
  'Population': 270324},
 {'ID': 138,
  'Name': 'Central Coast',
  'CountryCode': 'AUS',
  'District': 'New South Wales',
  'Population': 227657},
 {'ID': 139,
  'Name': 'Wollongong',
  'CountryCode': 'AUS',
  'District': 'New South Wales',
  'Population': 219761},
 {'ID': 140,
  'Name': 'Hobart',
  'CountryCode': 'AUS',
  'District': 'Tasmania',
  'Population': 126118},
 {'ID': 141,
  'Name': 'Geelong',
  'CountryCode': 'AUS',
  'District': 'Victoria',
  'Population': 125382},
 {'ID': 142,
  'Name': 'Townsville',
  'CountryCode': 'AUS',
  'District': 'Queensland',
  'Population': 109914},
 {'ID': 143,
  'Name': 'Cairns',
  'CountryCode': 'AUS',
  'District': 'Queensland',
  'Population': 92273},
 {'ID': 144,
  'Name': 'Baku',
  'CountryCode': 'AZE',
  'District': 'Baki',
  'Population': 1787800},
 {'ID': 145,
  'Name': 'Gäncä',
  'CountryCode': 'AZE',
  'District': 'Gäncä',
  'Population': 299300},
 {'ID': 146,
  'Name': 'Sumqayit',
  'CountryCode': 'AZE',
  'District': 'Sumqayit',
  'Population': 283000},
 {'ID': 147,
  'Name': 'Mingäçevir',
  'CountryCode': 'AZE',
  'District': 'Mingäçevir',
  'Population': 93900},
 {'ID': 148,
  'Name': 'Nassau',
  'CountryCode': 'BHS',
  'District': 'New Providence',
  'Population': 172000},
 {'ID': 149,
  'Name': 'al-Manama',
  'CountryCode': 'BHR',
  'District': 'al-Manama',
  'Population': 148000},
 {'ID': 150,
  'Name': 'Dhaka',
  'CountryCode': 'BGD',
  'District': 'Dhaka',
  'Population': 3612850},
 {'ID': 151,
  'Name': 'Chittagong',
  'CountryCode': 'BGD',
  'District': 'Chittagong',
  'Population': 1392860},
 {'ID': 152,
  'Name': 'Khulna',
  'CountryCode': 'BGD',
  'District': 'Khulna',
  'Population': 663340},
 {'ID': 153,
  'Name': 'Rajshahi',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 294056},
 {'ID': 154,
  'Name': 'Narayanganj',
  'CountryCode': 'BGD',
  'District': 'Dhaka',
  'Population': 202134},
 {'ID': 155,
  'Name': 'Rangpur',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 191398},
 {'ID': 156,
  'Name': 'Mymensingh',
  'CountryCode': 'BGD',
  'District': 'Dhaka',
  'Population': 188713},
 {'ID': 157,
  'Name': 'Barisal',
  'CountryCode': 'BGD',
  'District': 'Barisal',
  'Population': 170232},
 {'ID': 158,
  'Name': 'Tungi',
  'CountryCode': 'BGD',
  'District': 'Dhaka',
  'Population': 168702},
 {'ID': 159,
  'Name': 'Jessore',
  'CountryCode': 'BGD',
  'District': 'Khulna',
  'Population': 139710},
 {'ID': 160,
  'Name': 'Comilla',
  'CountryCode': 'BGD',
  'District': 'Chittagong',
  'Population': 135313},
 {'ID': 161,
  'Name': 'Nawabganj',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 130577},
 {'ID': 162,
  'Name': 'Dinajpur',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 127815},
 {'ID': 163,
  'Name': 'Bogra',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 120170},
 {'ID': 164,
  'Name': 'Sylhet',
  'CountryCode': 'BGD',
  'District': 'Sylhet',
  'Population': 117396},
 {'ID': 165,
  'Name': 'Brahmanbaria',
  'CountryCode': 'BGD',
  'District': 'Chittagong',
  'Population': 109032},
 {'ID': 166,
  'Name': 'Tangail',
  'CountryCode': 'BGD',
  'District': 'Dhaka',
  'Population': 106004},
 {'ID': 167,
  'Name': 'Jamalpur',
  'CountryCode': 'BGD',
  'District': 'Dhaka',
  'Population': 103556},
 {'ID': 168,
  'Name': 'Pabna',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 103277},
 {'ID': 169,
  'Name': 'Naogaon',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 101266},
 {'ID': 170,
  'Name': 'Sirajganj',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 99669},
 {'ID': 171,
  'Name': 'Narsinghdi',
  'CountryCode': 'BGD',
  'District': 'Dhaka',
  'Population': 98342},
 {'ID': 172,
  'Name': 'Saidpur',
  'CountryCode': 'BGD',
  'District': 'Rajshahi',
  'Population': 96777},
 {'ID': 173,
  'Name': 'Gazipur',
  'CountryCode': 'BGD',
  'District': 'Dhaka',
  'Population': 96717},
 {'ID': 174,
  'Name': 'Bridgetown',
  'CountryCode': 'BRB',
  'District': 'St Michael',
  'Population': 6070},
 {'ID': 175,
  'Name': 'Antwerpen',
  'CountryCode': 'BEL',
  'District': 'Antwerpen',
  'Population': 446525},
 {'ID': 176,
  'Name': 'Gent',
  'CountryCode': 'BEL',
  'District': 'East Flanderi',
  'Population': 224180},
 {'ID': 177,
  'Name': 'Charleroi',
  'CountryCode': 'BEL',
  'District': 'Hainaut',
  'Population': 200827},
 {'ID': 178,
  'Name': 'Liège',
  'CountryCode': 'BEL',
  'District': 'Liège',
  'Population': 185639},
 {'ID': 179,
  'Name': 'Bruxelles [Brussel]',
  'CountryCode': 'BEL',
  'District': 'Bryssel',
  'Population': 133859},
 {'ID': 180,
  'Name': 'Brugge',
  'CountryCode': 'BEL',
  'District': 'West Flanderi',

In [58]:
for table in liste_tables:
    db[table].insert_many([dict(zip(list(globals()[table]), e)) for e in globals()[table].values.tolist()])

In [ ]:
conn.close()

In [64]:
# Liste des villes de France
res = db.City.aggregate([
    { "$lookup": {
        "from": "Country",
        "localField": "CountryCode",
        "foreignField": "Code",
        "as": "Country"
    }},
    { "$match": { "Country.Name": "France" }}
])
pandas.DataFrame(res)

,_id,ID,Name,CountryCode,District,Population,Country
0,68d29ff1987faa03afc0efe6,2974,Paris,FRA,Île-de-France,2125246,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
1,68d29ff1987faa03afc0efe7,2975,Marseille,FRA,Provence-Alpes-Côte,798430,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
2,68d29ff1987faa03afc0efe8,2976,Lyon,FRA,Rhône-Alpes,445452,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
3,68d29ff1987faa03afc0efe9,2977,Toulouse,FRA,Midi-Pyrénées,390350,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
4,68d29ff1987faa03afc0efea,2978,Nice,FRA,Provence-Alpes-Côte,342738,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
5,68d29ff1987faa03afc0efeb,2979,Nantes,FRA,Pays de la Loire,270251,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
6,68d29ff1987faa03afc0efec,2980,Strasbourg,FRA,Alsace,264115,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
7,68d29ff1987faa03afc0efed,2981,Montpellier,FRA,Languedoc-Roussillon,225392,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
8,68d29ff1987faa03afc0efee,2982,Bordeaux,FRA,Aquitaine,215363,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
9,68d29ff1987faa03afc0efef,2983,Rennes,FRA,Haute-Normandie,206229,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
10,68d29ff1987faa03afc0eff0,2984,Le Havre,FRA,Champagne-Ardenne,190905,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
11,68d29ff1987faa03afc0eff1,2985,Reims,FRA,Nord-Pas-de-Calais,187206,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
12,68d29ff1987faa03afc0eff2,2986,Lille,FRA,Rhône-Alpes,184657,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
13,68d29ff1987faa03afc0eff3,2987,St-Étienne,FRA,Bretagne,180210,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
14,68d29ff1987faa03afc0eff4,2988,Toulon,FRA,Provence-Alpes-Côte,160639,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
15,68d29ff1987faa03afc0eff5,2989,Grenoble,FRA,Rhône-Alpes,153317,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
16,68d29ff1987faa03afc0eff6,2990,Angers,FRA,Pays de la Loire,151279,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
17,68d29ff1987faa03afc0eff7,2991,Dijon,FRA,Bourgogne,149867,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
18,68d29ff1987faa03afc0eff8,2992,Brest,FRA,Bretagne,149634,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
19,68d29ff1987faa03afc0eff9,2993,Le Mans,FRA,Pays de la Loire,146105,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
20,68d29ff1987faa03afc0effa,2994,Clermont-Ferrand,FRA,Auvergne,137140,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
21,68d29ff1987faa03afc0effb,2995,Amiens,FRA,Picardie,135501,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
22,68d29ff1987faa03afc0effc,2996,Aix-en-Provence,FRA,Provence-Alpes-Côte,134222,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
23,68d29ff1987faa03afc0effd,2997,Limoges,FRA,Limousin,133968,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
24,68d29ff1987faa03afc0effe,2998,Nîmes,FRA,Languedoc-Roussillon,133424,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
25,68d29ff1987faa03afc0efff,2999,Tours,FRA,Centre,132820,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
26,68d29ff1987faa03afc0f000,3000,Villeurbanne,FRA,Rhône-Alpes,124215,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
27,68d29ff1987faa03afc0f001,3001,Metz,FRA,Lorraine,123776,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
28,68d29ff1987faa03afc0f002,3002,Besançon,FRA,Franche-Comté,117733,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
29,68d29ff1987faa03afc0f003,3003,Caen,FRA,Basse-Normandie,113987,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
30,68d29ff1987faa03afc0f004,3004,Orléans,FRA,Centre,113126,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
31,68d29ff1987faa03afc0f005,3005,Mulhouse,FRA,Alsace,110359,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
32,68d29ff1987faa03afc0f006,3006,Rouen,FRA,Haute-Normandie,106592,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
33,68d29ff1987faa03afc0f007,3007,Boulogne-Billancourt,FRA,Île-de-France,106367,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
34,68d29ff1987faa03afc0f008,3008,Perpignan,FRA,Languedoc-Roussillon,105115,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
35,68d29ff1987faa03afc0f009,3009,Nancy,FRA,Lorraine,103605,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
36,68d29ff1987faa03afc0f00a,3010,Roubaix,FRA,Nord-Pas-de-Calais,96984,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
37,68d29ff1987faa03afc0f00b,3011,Argenteuil,FRA,Île-de-France,93961,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
38,68d29ff1987faa03afc0f00c,3012,Tourcoing,FRA,Nord-Pas-de-Calais,93540,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."
39,68d29ff1987faa03afc0f00d,3013,Montreuil,FRA,Île-de-France,90674,"[{'_id': 68d29ff1987faa03afc0f480, 'Code': 'FR..."

## Deuxième possibilité : une collection avec toutes les informations

In [76]:
liste_cities = [City.query("CountryCode == @e") for e in Country.Code]

In [81]:
liste_cities_propre = [[dict(zip(list(l), e)) for e in l.values.tolist()] for l in liste_cities]

In [85]:
Country_new = [dict(zip(list(Country), e)) for e in Country.values.tolist()]
Country_new

[{'Code': 'ABW',
  'Name': 'Aruba',
  'Continent': 'North America',
  'Region': 'Caribbean',
  'SurfaceArea': 193.0,
  'IndepYear': nan,
  'Population': 103000,
  'LifeExpectancy': 78.4,
  'GNP': 828.0,
  'GNPOld': 793.0,
  'LocalName': 'Aruba',
  'GovernmentForm': 'Nonmetropolitan Territory of The Netherlands',
  'HeadOfState': 'Beatrix',
  'Capital': 129.0,
  'Code2': 'AW'},
 {'Code': 'AFG',
  'Name': 'Afghanistan',
  'Continent': 'Asia',
  'Region': 'Southern and Central Asia',
  'SurfaceArea': 652090.0,
  'IndepYear': 1919.0,
  'Population': 22720000,
  'LifeExpectancy': 45.9,
  'GNP': 5976.0,
  'GNPOld': nan,
  'LocalName': 'Afganistan/Afqanestan',
  'GovernmentForm': 'Islamic Emirate',
  'HeadOfState': 'Mohammad Omar',
  'Capital': 1.0,
  'Code2': 'AF'},
 {'Code': 'AGO',
  'Name': 'Angola',
  'Continent': 'Africa',
  'Region': 'Central Africa',
  'SurfaceArea': 1246700.0,
  'IndepYear': 1975.0,
  'Population': 12878000,
  'LifeExpectancy': 38.3,
  'GNP': 6648.0,
  'GNPOld': 7984.0,
  'LocalName': 'Angola',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'José Eduardo dos Santos',
  'Capital': 56.0,
  'Code2': 'AO'},
 {'Code': 'AIA',
  'Name': 'Anguilla',
  'Continent': 'North America',
  'Region': 'Caribbean',
  'SurfaceArea': 96.0,
  'IndepYear': nan,
  'Population': 8000,
  'LifeExpectancy': 76.1,
  'GNP': 63.2,
  'GNPOld': nan,
  'LocalName': 'Anguilla',
  'GovernmentForm': 'Dependent Territory of the UK',
  'HeadOfState': 'Elisabeth II',
  'Capital': 62.0,
  'Code2': 'AI'},
 {'Code': 'ALB',
  'Name': 'Albania',
  'Continent': 'Europe',
  'Region': 'Southern Europe',
  'SurfaceArea': 28748.0,
  'IndepYear': 1912.0,
  'Population': 3401200,
  'LifeExpectancy': 71.6,
  'GNP': 3205.0,
  'GNPOld': 2500.0,
  'LocalName': 'Shqipëria',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Rexhep Mejdani',
  'Capital': 34.0,
  'Code2': 'AL'},
 {'Code': 'AND',
  'Name': 'Andorra',
  'Continent': 'Europe',
  'Region': 'Southern Europe',
  'SurfaceArea': 468.0,
  'IndepYear': 1278.0,
  'Population': 78000,
  'LifeExpectancy': 83.5,
  'GNP': 1630.0,
  'GNPOld': nan,
  'LocalName': 'Andorra',
  'GovernmentForm': 'Parliamentary Coprincipality',
  'HeadOfState': '',
  'Capital': 55.0,
  'Code2': 'AD'},
 {'Code': 'ANT',
  'Name': 'Netherlands Antilles',
  'Continent': 'North America',
  'Region': 'Caribbean',
  'SurfaceArea': 800.0,
  'IndepYear': nan,
  'Population': 217000,
  'LifeExpectancy': 74.7,
  'GNP': 1941.0,
  'GNPOld': nan,
  'LocalName': 'Nederlandse Antillen',
  'GovernmentForm': 'Nonmetropolitan Territory of The Netherlands',
  'HeadOfState': 'Beatrix',
  'Capital': 33.0,
  'Code2': 'AN'},
 {'Code': 'ARE',
  'Name': 'United Arab Emirates',
  'Continent': 'Asia',
  'Region': 'Middle East',
  'SurfaceArea': 83600.0,
  'IndepYear': 1971.0,
  'Population': 2441000,
  'LifeExpectancy': 74.1,
  'GNP': 37966.0,
  'GNPOld': 36846.0,
  'LocalName': 'Al-Imarat al-´Arabiya al-Muttahida',
  'GovernmentForm': 'Emirate Federation',
  'HeadOfState': 'Zayid bin Sultan al-Nahayan',
  'Capital': 65.0,
  'Code2': 'AE'},
 {'Code': 'ARG',
  'Name': 'Argentina',
  'Continent': 'South America',
  'Region': 'South America',
  'SurfaceArea': 2780400.0,
  'IndepYear': 1816.0,
  'Population': 37032000,
  'LifeExpectancy': 75.1,
  'GNP': 340238.0,
  'GNPOld': 323310.0,
  'LocalName': 'Argentina',
  'GovernmentForm': 'Federal Republic',
  'HeadOfState': 'Fernando de la Rúa',
  'Capital': 69.0,
  'Code2': 'AR'},
 {'Code': 'ARM',
  'Name': 'Armenia',
  'Continent': 'Asia',
  'Region': 'Middle East',
  'SurfaceArea': 29800.0,
  'IndepYear': 1991.0,
  'Population': 3520000,
  'LifeExpectancy': 66.4,
  'GNP': 1813.0,
  'GNPOld': 1627.0,
  'LocalName': 'Hajastan',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Robert Kotšarjan',
  'Capital': 126.0,
  'Code2': 'AM'},
 {'Code': 'ASM',
  'Name': 'American Samoa',
  'Continent': 'Oceania',
  'Region': 'Polynesia',
  'SurfaceArea': 199.0,
  'IndepYear': nan,
  'Population': 68000,
  'LifeExpectancy': 75.1,
  'GNP': 334.0,
  'GNPOld': nan,
  'LocalName': 'Amerika Samoa',
  'GovernmentForm': 'US Territory',
  'HeadOfState': 'George W. Bush',
  'Capital': 54.0,
  'Code2': 'AS'},
 {'Code': 'ATA',
  'Name': 'Antarctica',
  'Continent': 'Antarctica',
  'Region': 'Antarctica',
  'SurfaceArea': 13120000.0,
  'IndepYear': nan,
  'Population': 0,
  'LifeExpectancy': nan,
  'GNP': 0.0,
  'GNPOld': nan,
  'LocalName': '–',
  'GovernmentForm': 'Co-administrated',
  'HeadOfState': '',
  'Capital': nan,
  'Code2': 'AQ'},
 {'Code': 'ATF',
  'Name': 'French Southern territories',
  'Continent': 'Antarctica',
  'Region': 'Antarctica',
  'SurfaceArea': 7780.0,
  'IndepYear': nan,
  'Population': 0,
  'LifeExpectancy': nan,
  'GNP': 0.0,
  'GNPOld': nan,
  'LocalName': 'Terres australes françaises',
  'GovernmentForm': 'Nonmetropolitan Territory of France',
  'HeadOfState': 'Jacques Chirac',
  'Capital': nan,
  'Code2': 'TF'},
 {'Code': 'ATG',
  'Name': 'Antigua and Barbuda',
  'Continent': 'North America',
  'Region': 'Caribbean',
  'SurfaceArea': 442.0,
  'IndepYear': 1981.0,
  'Population': 68000,
  'LifeExpectancy': 70.5,
  'GNP': 612.0,
  'GNPOld': 584.0,
  'LocalName': 'Antigua and Barbuda',
  'GovernmentForm': 'Constitutional Monarchy',
  'HeadOfState': 'Elisabeth II',
  'Capital': 63.0,
  'Code2': 'AG'},
 {'Code': 'AUS',
  'Name': 'Australia',
  'Continent': 'Oceania',
  'Region': 'Australia and New Zealand',
  'SurfaceArea': 7741220.0,
  'IndepYear': 1901.0,
  'Population': 18886000,
  'LifeExpectancy': 79.8,
  'GNP': 351182.0,
  'GNPOld': 392911.0,
  'LocalName': 'Australia',
  'GovernmentForm': 'Constitutional Monarchy, Federation',
  'HeadOfState': 'Elisabeth II',
  'Capital': 135.0,
  'Code2': 'AU'},
 {'Code': 'AUT',
  'Name': 'Austria',
  'Continent': 'Europe',
  'Region': 'Western Europe',
  'SurfaceArea': 83859.0,
  'IndepYear': 1918.0,
  'Population': 8091800,
  'LifeExpectancy': 77.7,
  'GNP': 211860.0,
  'GNPOld': 206025.0,
  'LocalName': 'Österreich',
  'GovernmentForm': 'Federal Republic',
  'HeadOfState': 'Thomas Klestil',
  'Capital': 1523.0,
  'Code2': 'AT'},
 {'Code': 'AZE',
  'Name': 'Azerbaijan',
  'Continent': 'Asia',
  'Region': 'Middle East',
  'SurfaceArea': 86600.0,
  'IndepYear': 1991.0,
  'Population': 7734000,
  'LifeExpectancy': 62.9,
  'GNP': 4127.0,
  'GNPOld': 4100.0,
  'LocalName': 'Azärbaycan',
  'GovernmentForm': 'Federal Republic',
  'HeadOfState': 'Heydär Äliyev',
  'Capital': 144.0,
  'Code2': 'AZ'},
 {'Code': 'BDI',
  'Name': 'Burundi',
  'Continent': 'Africa',
  'Region': 'Eastern Africa',
  'SurfaceArea': 27834.0,
  'IndepYear': 1962.0,
  'Population': 6695000,
  'LifeExpectancy': 46.2,
  'GNP': 903.0,
  'GNPOld': 982.0,
  'LocalName': 'Burundi/Uburundi',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Pierre Buyoya',
  'Capital': 552.0,
  'Code2': 'BI'},
 {'Code': 'BEL',
  'Name': 'Belgium',
  'Continent': 'Europe',
  'Region': 'Western Europe',
  'SurfaceArea': 30518.0,
  'IndepYear': 1830.0,
  'Population': 10239000,
  'LifeExpectancy': 77.8,
  'GNP': 249704.0,
  'GNPOld': 243948.0,
  'LocalName': 'België/Belgique',
  'GovernmentForm': 'Constitutional Monarchy, Federation',
  'HeadOfState': 'Albert II',
  'Capital': 179.0,
  'Code2': 'BE'},
 {'Code': 'BEN',
  'Name': 'Benin',
  'Continent': 'Africa',
  'Region': 'Western Africa',
  'SurfaceArea': 112622.0,
  'IndepYear': 1960.0,
  'Population': 6097000,
  'LifeExpectancy': 50.2,
  'GNP': 2357.0,
  'GNPOld': 2141.0,
  'LocalName': 'Bénin',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Mathieu Kérékou',
  'Capital': 187.0,
  'Code2': 'BJ'},
 {'Code': 'BFA',
  'Name': 'Burkina Faso',
  'Continent': 'Africa',
  'Region': 'Western Africa',
  'SurfaceArea': 274000.0,
  'IndepYear': 1960.0,
  'Population': 11937000,
  'LifeExpectancy': 46.7,
  'GNP': 2425.0,
  'GNPOld': 2201.0,
  'LocalName': 'Burkina Faso',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Blaise Compaoré',
  'Capital': 549.0,
  'Code2': 'BF'},
 {'Code': 'BGD',
  'Name': 'Bangladesh',
  'Continent': 'Asia',
  'Region': 'Southern and Central Asia',
  'SurfaceArea': 143998.0,
  'IndepYear': 1971.0,
  'Population': 129155000,
  'LifeExpectancy': 60.2,
  'GNP': 32852.0,
  'GNPOld': 31966.0,
  'LocalName': 'Bangladesh',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Shahabuddin Ahmad',
  'Capital': 150.0,
  'Code2': 'BD'},
 {'Code': 'BGR',
  'Name': 'Bulgaria',
  'Continent': 'Europe',
  'Region': 'Eastern Europe',
  'SurfaceArea': 110994.0,
  'IndepYear': 1908.0,
  'Population': 8190900,
  'LifeExpectancy': 70.9,
  'GNP': 12178.0,
  'GNPOld': 10169.0,
  'LocalName': 'Balgarija',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Petar Stojanov',
  'Capital': 539.0,
  'Code2': 'BG'},
 {'Code': 'BHR',
  'Name': 'Bahrain',
  'Continent': 'Asia',
  'Region': 'Middle East',
  'SurfaceArea': 694.0,
  'IndepYear': 1971.0,
  'Population': 617000,
  'LifeExpectancy': 73.0,
  'GNP': 6366.0,
  'GNPOld': 6097.0,
  'LocalName': 'Al-Bahrayn',
  'GovernmentForm': 'Monarchy (Emirate)',
  'HeadOfState': 'Hamad ibn Isa al-Khalifa',
  'Capital': 149.0,
  'Code2': 'BH'},
 {'Code': 'BHS',
  'Name': 'Bahamas',
  'Continent': 'North America',
  'Region': 'Caribbean',
  'SurfaceArea': 13878.0,
  'IndepYear': 1973.0,
  'Population': 307000,
  'LifeExpectancy': 71.1,
  'GNP': 3527.0,
  'GNPOld': 3347.0,
  'LocalName': 'The Bahamas',
  'GovernmentForm': 'Constitutional Monarchy',
  'HeadOfState': 'Elisabeth II',
  'Capital': 148.0,
  'Code2': 'BS'},
 {'Code': 'BIH',
  'Name': 'Bosnia and Herzegovina',
  'Continent': 'Europe',
  'Region': 'Southern Europe',
  'SurfaceArea': 51197.0,
  'IndepYear': 1992.0,
  'Population': 3972000,
  'LifeExpectancy': 71.5,
  'GNP': 2841.0,
  'GNPOld': nan,
  'LocalName': 'Bosna i Hercegovina',
  'GovernmentForm': 'Federal Republic',
  'HeadOfState': 'Ante Jelavic',
  'Capital': 201.0,
  'Code2': 'BA'},
 {'Code': 'BLR',
  'Name': 'Belarus',
  'Continent': 'Europe',
  'Region': 'Eastern Europe',
  'SurfaceArea': 207600.0,
  'IndepYear': 1991.0,
  'Population': 10236000,
  'LifeExpectancy': 68.0,
  'GNP': 13714.0,
  'GNPOld': nan,
  'LocalName': 'Belarus',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Aljaksandr Lukašenka',
  'Capital': 3520.0,
  'Code2': 'BY'},
 {'Code': 'BLZ',
  'Name': 'Belize',
  'Continent': 'North America',
  'Region': 'Central America',
  'SurfaceArea': 22696.0,
  'IndepYear': 1981.0,
  'Population': 241000,
  'LifeExpectancy': 70.9,
  'GNP': 630.0,
  'GNPOld': 616.0,
  'LocalName': 'Belize',
  'GovernmentForm': 'Constitutional Monarchy',
  'HeadOfState': 'Elisabeth II',
  'Capital': 185.0,
  'Code2': 'BZ'},
 {'Code': 'BMU',
  'Name': 'Bermuda',
  'Continent': 'North America',
  'Region': 'North America',
  'SurfaceArea': 53.0,
  'IndepYear': nan,
  'Population': 65000,
  'LifeExpectancy': 76.9,
  'GNP': 2328.0,
  'GNPOld': 2190.0,
  'LocalName': 'Bermuda',
  'GovernmentForm': 'Dependent Territory of the UK',
  'HeadOfState': 'Elisabeth II',
  'Capital': 191.0,
  'Code2': 'BM'},
 {'Code': 'BOL',
  'Name': 'Bolivia',
  'Continent': 'South America',
  'Region': 'South America',
  'SurfaceArea': 1098581.0,
  'IndepYear': 1825.0,
  'Population': 8329000,
  'LifeExpectancy': 63.7,
  'GNP': 8571.0,
  'GNPOld': 7967.0,
  'LocalName': 'Bolivia',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Hugo Bánzer Suárez',
  'Capital': 194.0,
  'Code2': 'BO'},
 {'Code': 'BRA',
  'Name': 'Brazil',
  'Continent': 'South America',
  'Region': 'South America',
  'SurfaceArea': 8547403.0,
  'IndepYear': 1822.0,
  'Population': 170115000,
  'LifeExpectancy': 62.9,
  'GNP': 776739.0,
  'GNPOld': 804108.0,
  'LocalName': 'Brasil',
  'GovernmentForm': 'Federal Republic',
  'HeadOfState': 'Fernando Henrique Cardoso',
  'Capital': 211.0,
  'Code2': 'BR'},
 {'Code': 'BRB',
  'Name': 'Barbados',
  'Continent': 'North America',
  'Region': 'Caribbean',
  'SurfaceArea': 430.0,
  'IndepYear': 1966.0,
  'Population': 270000,
  'LifeExpectancy': 73.0,
  'GNP': 2223.0,
  'GNPOld': 2186.0,
  'LocalName': 'Barbados',
  'GovernmentForm': 'Constitutional Monarchy',
  'HeadOfState': 'Elisabeth II',
  'Capital': 174.0,
  'Code2': 'BB'},
 {'Code': 'BRN',
  'Name': 'Brunei',
  'Continent': 'Asia',
  'Region': 'Southeast Asia',
  'SurfaceArea': 5765.0,
  'IndepYear': 1984.0,
  'Population': 328000,
  'LifeExpectancy': 73.6,
  'GNP': 11705.0,
  'GNPOld': 12460.0,
  'LocalName': 'Brunei Darussalam',
  'GovernmentForm': 'Monarchy (Sultanate)',
  'HeadOfState': 'Haji Hassan al-Bolkiah',
  'Capital': 538.0,
  'Code2': 'BN'},
 {'Code': 'BTN',
  'Name': 'Bhutan',
  'Continent': 'Asia',
  'Region': 'Southern and Central Asia',
  'SurfaceArea': 47000.0,
  'IndepYear': 1910.0,
  'Population': 2124000,
  'LifeExpectancy': 52.4,
  'GNP': 372.0,
  'GNPOld': 383.0,
  'LocalName': 'Druk-Yul',
  'GovernmentForm': 'Monarchy',
  'HeadOfState': 'Jigme Singye Wangchuk',
  'Capital': 192.0,
  'Code2': 'BT'},
 {'Code': 'BVT',
  'Name': 'Bouvet Island',
  'Continent': 'Antarctica',
  'Region': 'Antarctica',
  'SurfaceArea': 59.0,
  'IndepYear': nan,
  'Population': 0,
  'LifeExpectancy': nan,
  'GNP': 0.0,
  'GNPOld': nan,
  'LocalName': 'Bouvetøya',
  'GovernmentForm': 'Dependent Territory of Norway',
  'HeadOfState': 'Harald V',
  'Capital': nan,
  'Code2': 'BV'},
 {'Code': 'BWA',
  'Name': 'Botswana',
  'Continent': 'Africa',
  'Region': 'Southern Africa',
  'SurfaceArea': 581730.0,
  'IndepYear': 1966.0,
  'Population': 1622000,
  'LifeExpectancy': 39.3,
  'GNP': 4834.0,
  'GNPOld': 4935.0,
  'LocalName': 'Botswana',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Festus G. Mogae',
  'Capital': 204.0,
  'Code2': 'BW'},
 {'Code': 'CAF',
  'Name': 'Central African Republic',
  'Continent': 'Africa',
  'Region': 'Central Africa',
  'SurfaceArea': 622984.0,
  'IndepYear': 1960.0,
  'Population': 3615000,
  'LifeExpectancy': 44.0,
  'GNP': 1054.0,
  'GNPOld': 993.0,
  'LocalName': 'Centrafrique/Bê-Afrîka',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Ange-Félix Patassé',
  'Capital': 1889.0,
  'Code2': 'CF'},
 {'Code': 'CAN',
  'Name': 'Canada',
  'Continent': 'North America',
  'Region': 'North America',
  'SurfaceArea': 9970610.0,
  'IndepYear': 1867.0,
  'Population': 31147000,
  'LifeExpectancy': 79.4,
  'GNP': 598862.0,
  'GNPOld': 625626.0,
  'LocalName': 'Canada',
  'GovernmentForm': 'Constitutional Monarchy, Federation',
  'HeadOfState': 'Elisabeth II',
  'Capital': 1822.0,
  'Code2': 'CA'},
 {'Code': 'CCK',
  'Name': 'Cocos (Keeling) Islands',
  'Continent': 'Oceania',
  'Region': 'Australia and New Zealand',
  'SurfaceArea': 14.0,
  'IndepYear': nan,
  'Population': 600,
  'LifeExpectancy': nan,
  'GNP': 0.0,
  'GNPOld': nan,
  'LocalName': 'Cocos (Keeling) Islands',
  'GovernmentForm': 'Territory of Australia',
  'HeadOfState': 'Elisabeth II',
  'Capital': 2317.0,
  'Code2': 'CC'},
 {'Code': 'CHE',
  'Name': 'Switzerland',
  'Continent': 'Europe',
  'Region': 'Western Europe',
  'SurfaceArea': 41284.0,
  'IndepYear': 1499.0,
  'Population': 7160400,
  'LifeExpectancy': 79.6,
  'GNP': 264478.0,
  'GNPOld': 256092.0,
  'LocalName': 'Schweiz/Suisse/Svizzera/Svizra',
  'GovernmentForm': 'Federation',
  'HeadOfState': 'Adolf Ogi',
  'Capital': 3248.0,
  'Code2': 'CH'},
 {'Code': 'CHL',
  'Name': 'Chile',
  'Continent': 'South America',
  'Region': 'South America',
  'SurfaceArea': 756626.0,
  'IndepYear': 1810.0,
  'Population': 15211000,
  'LifeExpectancy': 75.7,
  'GNP': 72949.0,
  'GNPOld': 75780.0,
  'LocalName': 'Chile',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Ricardo Lagos Escobar',
  'Capital': 554.0,
  'Code2': 'CL'},
 {'Code': 'CHN',
  'Name': 'China',
  'Continent': 'Asia',
  'Region': 'Eastern Asia',
  'SurfaceArea': 9572900.0,
  'IndepYear': -1523.0,
  'Population': 1277558000,
  'LifeExpectancy': 71.4,
  'GNP': 982268.0,
  'GNPOld': 917719.0,
  'LocalName': 'Zhongquo',
  'GovernmentForm': "People'sRepublic",
  'HeadOfState': 'Jiang Zemin',
  'Capital': 1891.0,
  'Code2': 'CN'},
 {'Code': 'CIV',
  'Name': 'Côte d’Ivoire',
  'Continent': 'Africa',
  'Region': 'Western Africa',
  'SurfaceArea': 322463.0,
  'IndepYear': 1960.0,
  'Population': 14786000,
  'LifeExpectancy': 45.2,
  'GNP': 11345.0,
  'GNPOld': 10285.0,
  'LocalName': 'Côte d’Ivoire',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Laurent Gbagbo',
  'Capital': 2814.0,
  'Code2': 'CI'},
 {'Code': 'CMR',
  'Name': 'Cameroon',
  'Continent': 'Africa',
  'Region': 'Central Africa',
  'SurfaceArea': 475442.0,
  'IndepYear': 1960.0,
  'Population': 15085000,
  'LifeExpectancy': 54.8,
  'GNP': 9174.0,
  'GNPOld': 8596.0,
  'LocalName': 'Cameroun/Cameroon',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Paul Biya',
  'Capital': 1804.0,
  'Code2': 'CM'},
 {'Code': 'COD',
  'Name': 'Congo, The Democratic Republic of the',
  'Continent': 'Africa',
  'Region': 'Central Africa',
  'SurfaceArea': 2344858.0,
  'IndepYear': 1960.0,
  'Population': 51654000,
  'LifeExpectancy': 48.8,
  'GNP': 6964.0,
  'GNPOld': 2474.0,
  'LocalName': 'République Démocratique du Congo',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Joseph Kabila',
  'Capital': 2298.0,
  'Code2': 'CD'},
 {'Code': 'COG',
  'Name': 'Congo',
  'Continent': 'Africa',
  'Region': 'Central Africa',
  'SurfaceArea': 342000.0,
  'IndepYear': 1960.0,
  'Population': 2943000,
  'LifeExpectancy': 47.4,
  'GNP': 2108.0,
  'GNPOld': 2287.0,
  'LocalName': 'Congo',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Denis Sassou-Nguesso',
  'Capital': 2296.0,
  'Code2': 'CG'},
 {'Code': 'COK',
  'Name': 'Cook Islands',
  'Continent': 'Oceania',
  'Region': 'Polynesia',
  'SurfaceArea': 236.0,
  'IndepYear': nan,
  'Population': 20000,
  'LifeExpectancy': 71.1,
  'GNP': 100.0,
  'GNPOld': nan,
  'LocalName': 'The Cook Islands',
  'GovernmentForm': 'Nonmetropolitan Territory of New Zealand',
  'HeadOfState': 'Elisabeth II',
  'Capital': 583.0,
  'Code2': 'CK'},
 {'Code': 'COL',
  'Name': 'Colombia',
  'Continent': 'South America',
  'Region': 'South America',
  'SurfaceArea': 1138914.0,
  'IndepYear': 1810.0,
  'Population': 42321000,
  'LifeExpectancy': 70.3,
  'GNP': 102896.0,
  'GNPOld': 105116.0,
  'LocalName': 'Colombia',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Andrés Pastrana Arango',
  'Capital': 2257.0,
  'Code2': 'CO'},
 {'Code': 'COM',
  'Name': 'Comoros',
  'Continent': 'Africa',
  'Region': 'Eastern Africa',
  'SurfaceArea': 1862.0,
  'IndepYear': 1975.0,
  'Population': 578000,
  'LifeExpectancy': 60.0,
  'GNP': 4401.0,
  'GNPOld': 4361.0,
  'LocalName': 'Komori/Comores',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Azali Assoumani',
  'Capital': 2295.0,
  'Code2': 'KM'},
 {'Code': 'CPV',
  'Name': 'Cape Verde',
  'Continent': 'Africa',
  'Region': 'Western Africa',
  'SurfaceArea': 4033.0,
  'IndepYear': 1975.0,
  'Population': 428000,
  'LifeExpectancy': 68.9,
  'GNP': 435.0,
  'GNPOld': 420.0,
  'LocalName': 'Cabo Verde',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'António Mascarenhas Monteiro',
  'Capital': 1859.0,
  'Code2': 'CV'},
 {'Code': 'CRI',
  'Name': 'Costa Rica',
  'Continent': 'North America',
  'Region': 'Central America',
  'SurfaceArea': 51100.0,
  'IndepYear': 1821.0,
  'Population': 4023000,
  'LifeExpectancy': 75.8,
  'GNP': 10226.0,
  'GNPOld': 9757.0,
  'LocalName': 'Costa Rica',
  'GovernmentForm': 'Republic',
  'HeadOfState': 'Miguel Ángel Rodríguez Echeverría',
  'Capital': 584.0,
  'Code2': 'CR'},
 {'Code': 'CUB',
  'Name': 'Cuba',
  'Continent': 'North America',
  'Region': 'Caribbean',
  'SurfaceArea': 110861.0,
  'IndepYear': 1902.0,
  'Population': 11201000,
  'LifeExpectancy': 76.2,
  'GNP': 17843.0,
  'GNPOld': 18862.0,
  'LocalName': 'Cuba',
  'GovernmentForm': 'Socialistic Republic',
  'HeadOfState': 'Fidel Castro Ruz',
  'Capital': 2413.0,
  'Code2': 'CU'},
 {'Code': 'CXR',
  'Name': 'Christmas Island',
  'Continent': 'Oceania',
  'Region': 'Australia and New Zealand',
  'SurfaceArea': 135.0,
  'IndepYear': nan,
  'Population': 2500,
  'LifeExpectancy': nan,
  'GNP': 0.0,

In [99]:
for e in Country_new:
    pays = e["Code"]
    liste_villes = City.query("CountryCode == @pays")
    liste_propre = [dict(zip(list(liste_villes), e)) for e in liste_villes.values.tolist()]
    e["Cities"] = liste_propre
    liste_langues = CountryLanguage.query("CountryCode == @pays")
    liste_propre2 = [dict(zip(list(liste_langues), e)) for e in liste_langues.values.tolist()]
    e["Langues"] = liste_propre2
Country_new[1]

{'Code': 'AFG',
 'Name': 'Afghanistan',
 'Continent': 'Asia',
 'Region': 'Southern and Central Asia',
 'SurfaceArea': 652090.0,
 'IndepYear': 1919.0,
 'Population': 22720000,
 'LifeExpectancy': 45.9,
 'GNP': 5976.0,
 'GNPOld': nan,
 'LocalName': 'Afganistan/Afqanestan',
 'GovernmentForm': 'Islamic Emirate',
 'HeadOfState': 'Mohammad Omar',
 'Capital': 1.0,
 'Code2': 'AF',
 'Cities': [{'ID': 1,
   'Name': 'Kabul',
   'CountryCode': 'AFG',
   'District': 'Kabol',
   'Population': 1780000},
  {'ID': 2,
   'Name': 'Qandahar',
   'CountryCode': 'AFG',
   'District': 'Qandahar',
   'Population': 237500},
  {'ID': 3,
   'Name': 'Herat',
   'CountryCode': 'AFG',
   'District': 'Herat',
   'Population': 186800},
  {'ID': 4,
   'Name': 'Mazar-e-Sharif',
   'CountryCode': 'AFG',
   'District': 'Balkh',
   'Population': 127800}],
 'Langues': [{'CountryCode': 'AFG',
   'Language': 'Balochi',
   'IsOfficial': 'F',
   'Percentage': 0.9},
  {'CountryCode': 'AFG',
   'Language': 'Dari',
   'IsOfficial': 'T',
   'Percentage': 32.1},
  {'CountryCode': 'AFG',
   'Language': 'Pashto',
   'IsOfficial': 'T',
   'Percentage': 52.4},
  {'CountryCode': 'AFG',
   'Language': 'Turkmenian',
   'IsOfficial': 'F',
   'Percentage': 1.9},
  {'CountryCode': 'AFG',
   'Language': 'Uzbek',
   'IsOfficial': 'F',
   'Percentage': 8.8}]}

In [101]:
db["CountryALL"].insert_many(Country_new)

InsertManyResult([ObjectId('68d2a59d987faa03afc0f8ff'), ObjectId('68d2a59d987faa03afc0f900'), ObjectId('68d2a59d987faa03afc0f901'), ObjectId('68d2a59d987faa03afc0f902'), ObjectId('68d2a59d987faa03afc0f903'), ObjectId('68d2a59d987faa03afc0f904'), ObjectId('68d2a59d987faa03afc0f905'), ObjectId('68d2a59d987faa03afc0f906'), ObjectId('68d2a59d987faa03afc0f907'), ObjectId('68d2a59d987faa03afc0f908'), ObjectId('68d2a59d987faa03afc0f909'), ObjectId('68d2a59d987faa03afc0f90a'), ObjectId('68d2a59d987faa03afc0f90b'), ObjectId('68d2a59d987faa03afc0f90c'), ObjectId('68d2a59d987faa03afc0f90d'), ObjectId('68d2a59d987faa03afc0f90e'), ObjectId('68d2a59d987faa03afc0f90f'), ObjectId('68d2a59d987faa03afc0f910'), ObjectId('68d2a59d987faa03afc0f911'), ObjectId('68d2a59d987faa03afc0f912'), ObjectId('68d2a59d987faa03afc0f913'), ObjectId('68d2a59d987faa03afc0f914'), ObjectId('68d2a59d987faa03afc0f915'), ObjectId('68d2a59d987faa03afc0f916'), ObjectId('68d2a59d987faa03afc0f917'), ObjectId('68d2a59d987faa03afc0f918'), ObjectId('68d2a59d987faa03afc0f919'), ObjectId('68d2a59d987faa03afc0f91a'), ObjectId('68d2a59d987faa03afc0f91b'), ObjectId('68d2a59d987faa03afc0f91c'), ObjectId('68d2a59d987faa03afc0f91d'), ObjectId('68d2a59d987faa03afc0f91e'), ObjectId('68d2a59d987faa03afc0f91f'), ObjectId('68d2a59d987faa03afc0f920'), ObjectId('68d2a59d987faa03afc0f921'), ObjectId('68d2a59d987faa03afc0f922'), ObjectId('68d2a59d987faa03afc0f923'), ObjectId('68d2a59d987faa03afc0f924'), ObjectId('68d2a59d987faa03afc0f925'), ObjectId('68d2a59d987faa03afc0f926'), ObjectId('68d2a59d987faa03afc0f927'), ObjectId('68d2a59d987faa03afc0f928'), ObjectId('68d2a59d987faa03afc0f929'), ObjectId('68d2a59d987faa03afc0f92a'), ObjectId('68d2a59d987faa03afc0f92b'), ObjectId('68d2a59d987faa03afc0f92c'), ObjectId('68d2a59d987faa03afc0f92d'), ObjectId('68d2a59d987faa03afc0f92e'), ObjectId('68d2a59d987faa03afc0f92f'), ObjectId('68d2a59d987faa03afc0f930'), ObjectId('68d2a59d987faa03afc0f931'), ObjectId('68d2a59d987faa03afc0f932'), ObjectId('68d2a59d987faa03afc0f933'), ObjectId('68d2a59d987faa03afc0f934'), ObjectId('68d2a59d987faa03afc0f935'), ObjectId('68d2a59d987faa03afc0f936'), ObjectId('68d2a59d987faa03afc0f937'), ObjectId('68d2a59d987faa03afc0f938'), ObjectId('68d2a59d987faa03afc0f939'), ObjectId('68d2a59d987faa03afc0f93a'), ObjectId('68d2a59d987faa03afc0f93b'), ObjectId('68d2a59d987faa03afc0f93c'), ObjectId('68d2a59d987faa03afc0f93d'), ObjectId('68d2a59d987faa03afc0f93e'), ObjectId('68d2a59d987faa03afc0f93f'), ObjectId('68d2a59d987faa03afc0f940'), ObjectId('68d2a59d987faa03afc0f941'), ObjectId('68d2a59d987faa03afc0f942'), ObjectId('68d2a59d987faa03afc0f943'), ObjectId('68d2a59d987faa03afc0f944'), ObjectId('68d2a59d987faa03afc0f945'), ObjectId('68d2a59d987faa03afc0f946'), ObjectId('68d2a59d987faa03afc0f947'), ObjectId('68d2a59d987faa03afc0f948'), ObjectId('68d2a59d987faa03afc0f949'), ObjectId('68d2a59d987faa03afc0f94a'), ObjectId('68d2a59d987faa03afc0f94b'), ObjectId('68d2a59d987faa03afc0f94c'), ObjectId('68d2a59d987faa03afc0f94d'), ObjectId('68d2a59d987faa03afc0f94e'), ObjectId('68d2a59d987faa03afc0f94f'), ObjectId('68d2a59d987faa03afc0f950'), ObjectId('68d2a59d987faa03afc0f951'), ObjectId('68d2a59d987faa03afc0f952'), ObjectId('68d2a59d987faa03afc0f953'), ObjectId('68d2a59d987faa03afc0f954'), ObjectId('68d2a59d987faa03afc0f955'), ObjectId('68d2a59d987faa03afc0f956'), ObjectId('68d2a59d987faa03afc0f957'), ObjectId('68d2a59d987faa03afc0f958'), ObjectId('68d2a59d987faa03afc0f959'), ObjectId('68d2a59d987faa03afc0f95a'), ObjectId('68d2a59d987faa03afc0f95b'), ObjectId('68d2a59d987faa03afc0f95c'), ObjectId('68d2a59d987faa03afc0f95d'), ObjectId('68d2a59d987faa03afc0f95e'), ObjectId('68d2a59d987faa03afc0f95f'), ObjectId('68d2a59d987faa03afc0f960'), ObjectId('68d2a59d987faa03afc0f961'), ObjectId('68d2a59d987faa03afc0f962'), ObjectId('68d2a59d987faa03afc0f963'), ObjectId('68d2a59d987faa03afc0f964'), ObjectId('68d2a59d987faa03afc0f965'), ObjectId('68d2a59d987faa03afc0f966'), ObjectId('68d2a59d987faa03afc0f967'), ObjectId('68d2a59d987faa03afc0f968'), ObjectId('68d2a59d987faa03afc0f969'), ObjectId('68d2a59d987faa03afc0f96a'), ObjectId('68d2a59d987faa03afc0f96b'), ObjectId('68d2a59d987faa03afc0f96c'), ObjectId('68d2a59d987faa03afc0f96d'), ObjectId('68d2a59d987faa03afc0f96e'), ObjectId('68d2a59d987faa03afc0f96f'), ObjectId('68d2a59d987faa03afc0f970'), ObjectId('68d2a59d987faa03afc0f971'), ObjectId('68d2a59d987faa03afc0f972'), ObjectId('68d2a59d987faa03afc0f973'), ObjectId('68d2a59d987faa03afc0f974'), ObjectId('68d2a59d987faa03afc0f975'), ObjectId('68d2a59d987faa03afc0f976'), ObjectId('68d2a59d987faa03afc0f977'), ObjectId('68d2a59d987faa03afc0f978'), ObjectId('68d2a59d987faa03afc0f979'), ObjectId('68d2a59d987faa03afc0f97a'), ObjectId('68d2a59d987faa03afc0f97b'), ObjectId('68d2a59d987faa03afc0f97c'), ObjectId('68d2a59d987faa03afc0f97d'), ObjectId('68d2a59d987faa03afc0f97e'), ObjectId('68d2a59d987faa03afc0f97f'), ObjectId('68d2a59d987faa03afc0f980'), ObjectId('68d2a59d987faa03afc0f981'), ObjectId('68d2a59d987faa03afc0f982'), ObjectId('68d2a59d987faa03afc0f983'), ObjectId('68d2a59d987faa03afc0f984'), ObjectId('68d2a59d987faa03afc0f985'), ObjectId('68d2a59d987faa03afc0f986'), ObjectId('68d2a59d987faa03afc0f987'), ObjectId('68d2a59d987faa03afc0f988'), ObjectId('68d2a59d987faa03afc0f989'), ObjectId('68d2a59d987faa03afc0f98a'), ObjectId('68d2a59d987faa03afc0f98b'), ObjectId('68d2a59d987faa03afc0f98c'), ObjectId('68d2a59d987faa03afc0f98d'), ObjectId('68d2a59d987faa03afc0f98e'), ObjectId('68d2a59d987faa03afc0f98f'), ObjectId('68d2a59d987faa03afc0f990'), ObjectId('68d2a59d987faa03afc0f991'), ObjectId('68d2a59d987faa03afc0f992'), ObjectId('68d2a59d987faa03afc0f993'), ObjectId('68d2a59d987faa03afc0f994'), ObjectId('68d2a59d987faa03afc0f995'), ObjectId('68d2a59d987faa03afc0f996'), ObjectId('68d2a59d987faa03afc0f997'), ObjectId('68d2a59d987faa03afc0f998'), ObjectId('68d2a59d987faa03afc0f999'), ObjectId('68d2a59d987faa03afc0f99a'), ObjectId('68d2a59d987faa03afc0f99b'), ObjectId('68d2a59d987faa03afc0f99c'), ObjectId('68d2a59d987faa03afc0f99d'), ObjectId('68d2a59d987faa03afc0f99e'), ObjectId('68d2a59d987faa03afc0f99f'), ObjectId('68d2a59d987faa03afc0f9a0'), ObjectId('68d2a59d987faa03afc0f9a1'), ObjectId('68d2a59d987faa03afc0f9a2'), ObjectId('68d2a59d987faa03afc0f9a3'), ObjectId('68d2a59d987faa03afc0f9a4'), ObjectId('68d2a59d987faa03afc0f9a5'), ObjectId('68d2a59d987faa03afc0f9a6'), ObjectId('68d2a59d987faa03afc0f9a7'), ObjectId('68d2a59d987faa03afc0f9a8'), ObjectId('68d2a59d987faa03afc0f9a9'), ObjectId('68d2a59d987faa03afc0f9aa'), ObjectId('68d2a59d987faa03afc0f9ab'), ObjectId('68d2a59d987faa03afc0f9ac'), ObjectId('68d2a59d987faa03afc0f9ad'), ObjectId('68d2a59d987faa03afc0f9ae'), ObjectId('68d2a59d987faa03afc0f9af'), ObjectId('68d2a59d987faa03afc0f9b0'), ObjectId('68d2a59d987faa03afc0f9b1'), ObjectId('68d2a59d987faa03afc0f9b2'), ObjectId('68d2a59d987faa03afc0f9b3'), ObjectId('68d2a59d987faa03afc0f9b4'), ObjectId('68d2a59d987faa03afc0f9b5'), ObjectId('68d2a59d987faa03afc0f9b6'), ObjectId('68d2a59d987faa03afc0f9b7'), ObjectId('68d2a59d987faa03afc0f9b8'), ObjectId('68d2a59d987faa03afc0f9b9'), ObjectId('68d2a59d987faa03afc0f9ba'), ObjectId('68d2a59d987faa03afc0f9bb'), ObjectId('68d2a59d987faa03afc0f9bc'), ObjectId('68d2a59d987faa03afc0f9bd'), ObjectId('68d2a59d987faa03afc0f9be'), ObjectId('68d2a59d987faa03afc0f9bf'), ObjectId('68d2a59d987faa03afc0f9c0'), ObjectId('68d2a59d987faa03afc0f9c1'), ObjectId('68d2a59d987faa03afc0f9c2'), ObjectId('68d2a59d987faa03afc0f9c3'), ObjectId('68d2a59d987faa03afc0f9c4'), ObjectId('68d2a59d987faa03afc0f9c5'), ObjectId('68d2a59d987faa03afc0f9c6'), ObjectId('68d2a59d987faa03afc0f9c7'), ObjectId('68d2a59d987faa03afc0f9c8'), ObjectId('68d2a59d987faa03afc0f9c9'), ObjectId('68d2a59d987faa03afc0f9ca'), ObjectId('68d2a59d987faa03afc0f9cb'), ObjectId('68d2a59d987faa03afc0f9cc'), ObjectId('68d2a59d987faa03afc0f9cd'), ObjectId('68d2a59d987faa03afc0f9ce'), ObjectId('68d2a59d987faa03afc0f9cf'), ObjectId('68d2a59d987faa03afc0f9d0'), ObjectId('68d2a59d987faa03afc0f9d1'), ObjectId('68d2a59d987faa03afc0f9d2'), ObjectId('68d2a59d987faa03afc0f9d3'), ObjectId('68d2a59d987faa03afc0f9d4'), ObjectId('68d2a59d987faa03afc0f9d5'), ObjectId('68d2a59d987faa03afc0f9d6'), ObjectId('68d2a59d987faa03afc0f9d7'), ObjectId('68d2a59d987faa03afc0f9d8'), ObjectId('68d2a59d987faa03afc0f9d9'), ObjectId('68d2a59d987faa03afc0f9da'), ObjectId('68d2a59d987faa03afc0f9db'), ObjectId('68d2a59d987faa03afc0f9dc'), ObjectId('68d2a59d987faa03afc0f9dd'), ObjectId('68d2a59d987faa03afc0f9de'), ObjectId('68d2a59d987faa03afc0f9df'), ObjectId('68d2a59d987faa03afc0f9e0'), ObjectId('68d2a59d987faa03afc0f9e1'), ObjectId('68d2a59d987faa03afc0f9e2'), ObjectId('68d2a59d987faa03afc0f9e3'), ObjectId('68d2a59d987faa03afc0f9e4'), ObjectId('68d2a59d987faa03afc0f9e5'), ObjectId('68d2a59d987faa03afc0f9e6'), ObjectId('68d2a59d987faa03afc0f9e7'), ObjectId('68d2a59d987faa03afc0f9e8'), ObjectId('68d2a59d987faa03afc0f9e9'), ObjectId('68d2a59d987faa03afc0f9ea'), ObjectId('68d2a59d987faa03afc0f9eb'), ObjectId('68d2a59d987faa03afc0f9ec'), ObjectId('68d2a59d987faa03afc0f9ed')], acknowledged=True)

In [105]:
# Liste des villes de France
res = db.CountryALL.aggregate([
    { "$match": { "Name": "France" }},
    { "$unwind": "$Cities" },
    { "$project": { "_id": 0, "Ville": "$Cities.Name" }}
])
pandas.DataFrame(res)

                   Ville
0                  Paris
1              Marseille
2                   Lyon
3               Toulouse
4                   Nice
5                 Nantes
6             Strasbourg
7            Montpellier
8               Bordeaux
9                 Rennes
10              Le Havre
11                 Reims
12                 Lille
13            St-Étienne
14                Toulon
15              Grenoble
16                Angers
17                 Dijon
18                 Brest
19               Le Mans
20      Clermont-Ferrand
21                Amiens
22       Aix-en-Provence
23               Limoges
24                 Nîmes
25                 Tours
26          Villeurbanne
27                  Metz
28              Besançon
29                  Caen
30               Orléans
31              Mulhouse
32                 Rouen
33  Boulogne-Billancourt
34             Perpignan
35                 Nancy
36               Roubaix
37            Argenteuil
38             Tourcoing
39             Montreuil